##### Config file #####

sample:
  healthy: "/home/users/astar/gis/carriehc/scratch-LOCCG/carriehc/bcbio/bams_for_hanae/CRC-986_300316_P-T-ready.bam"
  tumor: "/home/users/astar/gis/carriehc/scratch-LOCCG/carriehc/bcbio/bams_for_hanae/CRC-986_110215_P-T-ready.bam"
  buffycoat: "/home/users/astar/gis/carriehc/scratch-LOCCG/carriehc/bcbio/bams_for_hanae/CRC-986-N_WES.bam"

samplename:
  healthy: "CRC-986_300316-CW-T"
  tumor: "CRC-986_100215-CW-T"
  buffycoat: "CRC-986-CW-N"

dilutionfactors: "1000-0 1000-1000 750-1250 500-1500 400-1600 200-1800 100-1900 1000-1900"

chr: 'all'

healthydir: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data_wes/initialsamples/initialsamples_chr1/initialsamples_chr1_CRC-986_300316-CW-T"
tumordir: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data_wes/initialsamples/initialsamples_chr1/initialsamples_chr1_CRC-986_100215-CW-T"
buffycoatdir: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data_wes/initialsamples/initialsamples_chr1/initialsamples_chr1_CRC-986-CW-N"
outputfolder: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data_wes/mixtures/mixtures_chr1"

tffile: "/home/users/astar/gis/carriehc/cfdna_snv_benchmark/data/extdata/ctDNA_burden_estimation_deepwgs_plasma_CRC_samples.csv" 
ichorcnaextdata: "/home/users/astar/gis/carriehc/.conda/envs/default/lib/R/library/ichorCNA/extdata/"
samtools: "/home/users/astar/gis/carriehc/.conda/envs/default/bin/samtools"
condapath: "/apps/anaconda3-individual-edition/2020.11/etc/profile.d/conda.sh"
bedfile: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/extdata/exome_chr1.bed"
machine: 'Pluto'
repopath: "/home/users/astar/gis/carriehc/"
