##### Config file #####

sample:
  healthy: "/mnt/projects/huangwt/wgs/hanae/lowtbcfdnabams/NCC_CRC-1014_090516-CW-T-sort.bam"
  tumor: "/mnt/projects/skanderupamj/wgs/data/training/ready.bams/cfdna/NCC_CRC-1014_180816-CW-T-ready.bam"
  buffycoat: "/mnt/projects/skanderupamj/wgs/data/training/ready.bams/cfdna/NCC_CRC-1014_180816-CW-N-ready.bam"

samplename:
  healthy: "CRC-1014_090516-CW-T"
  tumor: "CRC-1014_180816-CW-T"
  buffycoat: "CRC-1014_180816-CW-N"

dilutionfactors: "70-0 70-80 50-100 30-120 20-130 10-140 5-145 70-30 70-130 70-180"

chr: 22

healthydir: "/mnt/projects/zhug/cfDNA/skandlab-public/carriehc/data/initialsamples/initialsamples_chr22/initialsamples_chr22_CRC-1014_090516-CW-T"
tumordir: "/mnt/projects/zhug/cfDNA/skandlab-public/carriehc/data/initialsamples/initialsamples_chr22/initialsamples_chr22_NCC_CRC-1014_180816-CW-T"
buffycoatdir: "/mnt/projects/zhug/cfDNA/skandlab-public/carriehc/data/initialsamples/initialsamples_chr22/initialsamples_chr22_CRC-1014_180816-CW-N"
outputfolder: "/mnt/projects/zhug/cfDNA/skandlab-public/carriehc/data/mixtures/mixtures_chr22"

tffile: "/mnt/projects/carriehc/cfDNA/cfdna_snv/cfdna_snv_benchmark/dilutions/ctDNA_burden_estimation_deepwgs_plasma_CRC_samples.csv"
ichorcnaextdata: "/mnt/projects/carriehc/cfDNA/anaconda3/envs/ichorcna/lib/R/library/ichorCNA/extdata/"
samtools: "/mnt/projects/skanderupamj/wgs/bcbio_v107/bin/samtools"
