##### Config file #####

sample:
  healthy: "/mnt/projects/carriehc/cfDNA/data/healthy_chr22_merged-ready_986_filter_snv.sorted.bam" #/mnt/projects/carriehc/cfDNA/cfSNV/benchmark/healthy/healthy/healthy_chr22_merged-ready.bam 
  tumor: "/mnt/projects/skanderupamj/wgs/data/training/ready.bams/cfdna/NCC_CRC-986_100215-CW-T-ready.bam"
  buffycoat: "/mnt/projects/skanderupamj/wgs/data/training/ready.bams/cfdna/NCC_CRC-986_100215-CW-N-ready.bam"

samplename:
  healthy: "pooledhealthy"
  tumor: "CRC-986_100215"
  buffycoat: "CRC-986_100215-BC"

dilutionfactors: "1-0 1-0.72 0.75-0.765 0.5-0.81 0.25-0.855 0.125-0.875"

chr: 22

healthydir: "/mnt/projects/carriehc/cfDNA/cfdna_snv/cfdna_snv_benchmark/data/dilutions_series_chr22/pooledhealthy_snv/"
tumordir: "/mnt/projects/carriehc/cfDNA/cfdna_snv/cfdna_snv_benchmark/data/dilutions_series_chr22/NCC_CRC-986_100215-CW-T"
buffycoatdir: "/mnt/projects/carriehc/cfDNA/cfdna_snv/cfdna_snv_benchmark/data/dilutions_series_chr22/NCC_CRC-986_100215-CW-N"
outputfolder: "/mnt/projects/carriehc/cfDNA/cfdna_snv/cfdna_snv_benchmark/data/dilutions_series_chr22"

tffile: "/mnt/projects/carriehc/cfDNA/cfdna_snv/cfdna_snv_benchmark/dilutions/ctDNA_burden_estimation_deepwgs_plasma_CRC_samples.csv"
