##### Config file #####

sample:
  pseudohealthy: "/mnt/projects/huangwt/wgs/hanae/lowtbcfdnabams/NCC_CRC-1014_090516-CW-T-sort.bam"
  buffycoat: "/mnt/projects/skanderupamj/wgs/data/training/ready.bams/cfdna/NCC_CRC-1014_180816-CW-N-ready.bam"

samplename:
  pseudohealthy: "CRC-1014_090516-CW-T"
  buffycoat: "CRC-1014_180816-CW-N"

vafs: "0.3 0.2 0.15 0.10 0.05 0.025 0.01"

chr: 22

pseudohealthydir: "/mnt/projects/zhug/cfDNA/skandlab-public/carriehc/data/initialsamples/initialsamples_chr22/initialsamples_chr22_CRC-1014_090516-CW-T"
buffycoatdir: "/mnt/projects/zhug/cfDNA/skandlab-public/carriehc/data/initialsamples/initialsamples_chr22/initialsamples_chr22_CRC-1014_180816-CW-N"
outputfolder: "/mnt/projects/zhug/cfDNA/skandlab-public/carriehc/data/spikeins/spikekins_chr22"

mutsbed: '/mnt/projects/carriehc/cfDNA/cfdna_snv/cfdna_snv_benchmark/data/extdata/cosmic_mutations_atleast5patients/CRC_chr22_INDEL_vaf1.bed'
type: 'INDEL'

refgenome: "/mnt/projects/carriehc/cfDNA/data/refgenome/GRCh37/GRCh37.fa"
picardjarfile: "/mnt/projects/carriehc/cfDNA/utils/picard.jar"
aligner: mem
mindepth: 0
maxdepth: 200000
samtools: '/mnt/projects/skanderupamj/wgs/bcbio_v107/bin/samtools'
