##### Config file #####

sample:
  pseudohealthy: "/mnt/data/rawdata/986_300316_P-T-sort.bam"
  buffycoat: "/mnt/data/rawdata/986_300316_P-N-sort.bam"

samplename:
  knowntumormuts: "CRC-COSMIC-5p"
  pseudohealthy: "CRC-986_300316-CW-T"
  buffycoat: "CRC-986-CW-N"

vafs: "0.2 0.15 0.10 0.05 0.025 0.01 1"

chr: 13

pseudohealthydir: "/mnt/cfdnaseries/initialsamples/initialsamples_chr13/initialsamples_chr13_CRC-986_300316-CW-T"
buffycoatdir: "/mnt/cfdnaseries/initialsamples/initialsamples_chr13/initialsamples_chr13_CRC-986-CW-N"
outputfolder: "/mnt/cfdnaseries/spikeins/spikeins_chr13"

mutsbed:
  snv: '/home/ubuntu/cfdna_snv_benchmark/data/extdata/cosmic_mutations_atleast5patients/CRC_chr13_SNV_vaf1.bed'
  indel: '/home/ubuntu/cfdna_snv_benchmark/data/extdata/cosmic_mutations_atleast5patients/CRC_chr13_INDEL_vaf1.bed'

dilutionfactor:
  pseudohealthy: 150

refgenome: "/home/ubuntu/refgenome/GRCh37/GRCh37.fa"
picardjarfile: "/home/ubuntu/picard-tools-1.131/picard.jar"
aligner: mem
mindepth: 0
maxdepth: 200000
samtools: '/home/ubuntu/anaconda3/envs/default/bin/samtools'
bamsurgeonpath: '/home/ubuntu/'

machine: "Ronin"
condapath: "/home/ubuntu/anaconda3/etc/profile.d/conda.sh"
repopath: "/home/ubuntu/"
