##### Config file #####

sample:
  pseudohealthy: "/mnt/data/rawdata/1014_090516_P-T-sort.bam"
  buffycoat: "/mnt/data/rawdata/1014_090516_P-N-sort.bam"

samplename:
  knowntumormuts: "CRC-COSMIC-5p"
  pseudohealthy: "CRC-1014_090516-CW-T"
  buffycoat: "CRC-1014-CW-N"

vafs: "0.2 0.15 0.10 0.05 0.025 0.01 0"

chr: 5

pseudohealthydir: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data/initialsamples/initialsamples_chr5/initialsamples_chr5_CRC-1014_090516-CW-T"
buffycoatdir: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data/initialsamples/initialsamples_chr5/initialsamples_chr5_CRC-1014-CW-N"
outputfolder: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data/spikeins/spikeins_chr5"

mutsbed:
  snv: '/home/users/astar/gis/carriehc/cfdna_snv_benchmark/data/extdata/cosmic_mutations_atleast5patients/CRC_chr5_SNV_vaf1.bed'
  indel: '/home/users/astar/gis/carriehc/cfdna_snv_benchmark/data/extdata/cosmic_mutations_atleast5patients/CRC_chr5_INDEL_vaf1.bed'

dilutionfactor:
  pseudohealthy: 150

defaultbash: "/home/users/astar/gis/carriehc/cfdna_snv_benchmark/spikeins/run_sampleid.sh"

refgenome: "/home/users/astar/gis/carriehc/refgenome/GRCh37/GRCh37.fa"
picardjarfile: "/home/users/astar/gis/carriehc/utils/picard.jar"
aligner: mem
mindepth: 0
maxdepth: 200000
samtools: '/home/users/astar/gis/carriehc/.conda/envs/default/bin/samtools'
bamsurgeonpath: '/home/users/astar/gis/carriehc/'

machine: "Pluto"
condapath: "/apps/anaconda3-individual-edition/2020.11/etc/profile.d/conda.sh"
repopath: "/home/users/astar/gis/carriehc/"
