############# Config file ############

dilutionseriesfolder: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data/mixtures/mixtures_chr3/mixtures_chr3_CRC-986_100215-CW-T_CRC-986_300316-CW-T"
buffycoatbam: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data/initialsamples/initialsamples_chr3/initialsamples_chr3_CRC-986-CW-N/CRC-986-CW-N_chr3.bam"
chr: 3
extdata: /rfs-storageservice/GIS/Projects/LOCCG/carriehc/extdata/
outdir: /rfs-storageservice/GIS/Projects/LOCCG/carriehc/abemus_outdir/mixtures_chr3_CRC-986_100215-CW-T_CRC-986_300316-CW-T/
finaloutdir: /rfs-storageservice/GIS/Projects/LOCCG/carriehc/cfdna_callers/mixtures_chr3_CRC-986_100215-CW-T_CRC-986_300316-CW-T/
mode: 'wholegenome'
panelofnormalbcdir: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data/PoNbuffycoat/"

condapath: "/apps/anaconda3-individual-edition/2020.11/etc/profile.d/conda.sh"
repopath: "/home/users/astar/gis/carriehc/cfdna_snv_benchmark/callers"
