############# Config file ############

dilutionseriesfolder: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data/mixtures/mixtures_chr5/mixtures_chr5_CRC-986_100215-CW-T_CRC-986_300316-CW-T"
buffycoatbam: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data/initialsamples/initialsamples_chr5/initialsamples_chr5_CRC-986-CW-N/CRC-986-CW-N_chr5.bam"
chr: 5
extdata: /rfs-storageservice/GIS/Projects/LOCCG/carriehc/extdata/
outdir: /rfs-storageservice/GIS/Projects/LOCCG/carriehc/abemus_outdir/mixtures_chr5_CRC-986_100215-CW-T_CRC-986_300316-CW-T/
finaloutdir: /rfs-storageservice/GIS/Projects/LOCCG/carriehc/cfdna_callers/mixtures_chr5_CRC-986_100215-CW-T_CRC-986_300316-CW-T/
mode: 'exome'
panelofnormalbcdir: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data/PoNbuffycoat/"

condapath: "/apps/anaconda3-individual-edition/2020.11/etc/profile.d/conda.sh"
repopath: "/home/users/astar/gis/carriehc/cfdna_snv_benchmark/callers"
