############# Config file ############

dilutionseriesfolder: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data/mixtures/mixtures_chr11/mixtures_chr11_CRC-123_310715-CW-T_CRC-123_121115-CW-T"
buffycoatbam: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data/initialsamples/initialsamples_chr11/initialsamples_chr11_CRC-123-CW-N/CRC-123-CW-N_chr11.bam"
chr: 11
extdata: /rfs-storageservice/GIS/Projects/LOCCG/carriehc/extdata/
outdir: /rfs-storageservice/GIS/Projects/LOCCG/carriehc/abemus_outdir/mixtures_chr11_CRC-123_310715-CW-T_CRC-123_121115-CW-T/
finaloutdir: /rfs-storageservice/GIS/Projects/LOCCG/carriehc/cfdna_callers/mixtures_chr11_CRC-123_310715-CW-T_CRC-123_121115-CW-T/
mode: 'exome'
panelofnormalbcdir: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data/PoNbuffycoat/"

condapath: "/apps/anaconda3-individual-edition/2020.11/etc/profile.d/conda.sh"
repopath: "/home/users/astar/gis/carriehc/cfdna_snv_benchmark/callers"
