## Params ##

dilutionseriesfolder: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data/mixtures/mixtures_chr1/mixtures_chr1_CRC-986_100215-CW-T_CRC-986_300316-CW-T/"
buffycoatbam: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/data/initialsamples/initialsamples_chr1/initialsamples_chr1_CRC-986-CW-N/CRC-986-CW-N_chr1.bam"
chr: 1
tmpdir: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/Rlibs/cfSNV/extdata/tmp"
extdata: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/extdata/"
outdir: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/cfsnv_outdir/mixtures_chr1_CRC-986_100215-CW-T_CRC-986_300316-CW-T/"
finaloutdir : "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/cfdna_callers/mixtures_chr1_CRC-986_100215-CW-T_CRC-986_300316-CW-T/"
preprocessing: 'true'

condapath: "/apps/anaconda3-individual-edition/2020.11/etc/profile.d/conda.sh"
repopath: "/home/users/astar/gis/carriehc/cfdna_snv_benchmark/callers"
dir:
        samtools: "/home/users/astar/gis/carriehc/.conda/envs/cfSNV/bin/samtools"
        picard: "/home/users/astar/gis/carriehc/.conda/envs/cfSNV/share/picard-2.27.3-0/picard.jar"
        bedtools: "/home/users/astar/gis/carriehc/.conda/envs/cfSNV/bin/bedtools"
        GATK: "/home/users/astar/gis/carriehc/.conda/envs/cfSNV/opt/gatk-3.8/GenomeAnalysisTK.jar"
        bwa: "/home/users/astar/gis/carriehc/.conda/envs/cfSNV/bin/bwa"
        flash: "/home/users/astar/gis/carriehc/.conda/envs/cfSNV/bin/flash2"
        python: "/apps/anaconda3-individual-edition/2020.11/bin/python"
        java: "/home/users/astar/gis/carriehc/.conda/envs/cfSNV/bin/java"

