## Params ###

dilutionseriesfolder: "/outdir/data/mixtures/mixtures_chr18/mixtures_chr18_CRC-986_100215-CW-T_CRC-986_300316-CW-T/"
buffycoatbam: "/outdir/data/initialsamples/initialsamples_chr18/initialsamples_chr18_CRC-986-CW-N/CRC-986-CW-N_chr18.bam"
chr: 18
tmpdir: '/outdir/Rlibs/cfSNV/extdata/tmp'
extdata: '/outdir/extdata/'
outdir: "/outdir/cfsnv_outdir/mixtures_chr18_CRC-986_100215-CW-T_CRC-986_300316-CW-T/"
finaloutdir: '/outdir/cfdna_callers/mixtures_chr18_CRC-986_100215-CW-T_CRC-986_300316-CW-T/'
preprocessing: 'true'

dir:
        samtools: "/home/ubuntu/anaconda3/envs/cfSNV/bin/samtools"
        picard: "/home/ubuntu/anaconda3/envs/cfSNV/share/picard-2.26.10-0/picard.jar"
        bedtools: "/home/ubuntu/anaconda3/envs/cfSNV/bin/bedtools"
        GATK: "/home/ubuntu/anaconda3/envs/cfSNV/opt/gatk-3.8/GenomeAnalysisTK.jar"
        bwa: "/home/ubuntu/anaconda3/envs/cfSNV/bin/bwa"
        flash: "/home/ubuntu/anaconda3/envs/cfSNV/bin/flash2"
        python: "/home/ubuntu/anaconda3/envs/cfSNV/bin/python"
        java: 'java'


